### ISSUE TITLE
Great! But how can I switch languages?

### ISSUE THREAD

**Issue by manuel-reil** [thriqon/ember-cli-format-number#18]
Hi,

thank you for the efforts encapsulating numeral.js into an ember helper.
But how can I best define languages and select them?

Thank you,
Manuel

**Comment by thriqon** [comment]
Well, that is not really implemented yet (read: I didn't have the need, so I didn't do it). If you want to take a stab at it... I'd be delighted to receive a PR ;-)

**Comment by thriqon** [comment]
After taking a look into it, I can say that is definitely possible to define langauges and set the language, even with the current release. You can get access to the actual `numeral` function via `import numeral from 'numeral'`, e.g.:

    import numeral from 'numeral';
    numeral.language('fr', ...');
    numeral.language('fr');

You can do this for example in an instance initializer. Please note however that already rendered numbers will *not* update themselves as of yet. Is this enough for you?

**Comment by manuel-reil** [comment]
Thank you! That's easier than expected and elegant.
