### ISSUE TITLE
Version 2.0 Code and Tag

### ISSUE THREAD

**Issue by nbibler** [thriqon/ember-cli-format-number#81]
According to NPM:

![image](https://cloud.githubusercontent.com/assets/3775/20154903/811cd6ba-a697-11e6-9532-ccdaa6ab96d9.png)

However, GitHub only shows tags up to v1.1.0 and master's [package.json](https://github.com/thriqon/ember-cli-format-number/blob/e90c9e1c760c0989d47b9b36d649cd3efff8951e/package.json) matches that 1.1.0 version number.

Is there unpublished code somewhere for the 2.0 release? What are the changes?

**Comment by thriqon** [comment]
My bad :( I released NPM and tagged my local Git repo, but forgot to `git push`. Will do that as soon as I'm on my laptop again (Sunday).

There are no functional changes, the main reason for releasing a v2 was #74 . This makes the project setup way leaner, but it changes behavior.

**Comment by thriqon** [comment]
I just pushed the tag that was used to create 2.0. Sorry for the waiting. Let me know if you need anything else :)
